// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOCsTiDUJfRxhssm8mvyktuRibF_7nlc',
    appId: '1:472763261444:web:fcaf390619ea2fc8f1cb51',
    messagingSenderId: '472763261444',
    projectId: 'real-time-network-monitoring',
    authDomain: 'real-time-network-monitoring.firebaseapp.com',
    storageBucket: 'real-time-network-monitoring.firebasestorage.app',
    measurementId: 'G-WBCJFLS3S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQfAHfKBNesKWPYXIL_PiL_uF9n5NcTY',
    appId: '1:472763261444:android:47e62010dc360e10f1cb51',
    messagingSenderId: '472763261444',
    projectId: 'real-time-network-monitoring',
    storageBucket: 'real-time-network-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgMR-mRflsRMNvV5gkYEou3zaGCbzgn8A',
    appId: '1:472763261444:ios:c71a30fb0ab10ae9f1cb51',
    messagingSenderId: '472763261444',
    projectId: 'real-time-network-monitoring',
    storageBucket: 'real-time-network-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.realTimeNetMonitoringSys',
  );
}
